
/gate/world/daughters/name Upper
/gate/world/daughters/insert box
/gate/Upper/setMaterial Tungsten
/gate/Upper/geometry/setXLength 15 cm
/gate/Upper/geometry/setYLength 15 cm
/gate/Upper/geometry/setZLength 10 cm
/gate/Upper/vis/forceSolid
/gate/Upper/vis/setColor red
/gate/Upper/placement/setTranslation 0. 0. 30. cm 

/gate/world/daughters/name Lower1
/gate/world/daughters/insert box
/gate/Lower1/setMaterial Tungsten
/gate/Lower1/geometry/setXLength 8 cm
/gate/Lower1/geometry/setYLength 8 cm
/gate/Lower1/geometry/setZLength 4 cm
/gate/Lower1/vis/forceSolid
/gate/Lower1/vis/setColor red
/gate/Lower1/placement/setTranslation 0. 5. 43. cm 
/gate/Lower1/placement/setRotationAxis 1 0 0
/gate/Lower1/placement/setRotationAngle  350 deg

/gate/world/daughters/name Lower2
/gate/world/daughters/insert box
/gate/Lower2/setMaterial Tungsten
/gate/Lower2/geometry/setXLength 8 cm
/gate/Lower2/geometry/setYLength 8 cm
/gate/Lower2/geometry/setZLength 4 cm
/gate/Lower2/vis/forceSolid
/gate/Lower2/vis/setColor red
/gate/Lower2/placement/setTranslation 0. -5. 43. cm 
/gate/Lower2/placement/setRotationAxis 1 0 0
/gate/Lower2/placement/setRotationAngle  10 deg

