
/gate/world/daughters/name                  primary_collimator
/gate/world/daughters/insert                      cone
/gate/primary_collimator/setMaterial        Tungsten      
/gate/primary_collimator/geometry/setRmin2        6.45 mm
/gate/primary_collimator/geometry/setRmax2        82 mm
/gate/primary_collimator/geometry/setRmin1        31.45 mm
/gate/primary_collimator/geometry/setRmax1        82 mm
/gate/primary_collimator/geometry/setHeight       101 mm
/gate/primary_collimator/placement/setTranslation 0 0 -20 cm
/gate/primary_collimator/vis/setColor             blue
/gate/primary_collimator/vis/setVisible           1

