# -----------------------------------------------------
# FLATTENING_FILTER
# -----------------------------------------------------

/gate/world/daughters/name                       flattening_filter
/gate/world/daughters/insert                     cylinder
/gate/flattening_filter/setMaterial              Air
/gate/flattening_filter/geometry/setRmin         0 cm  
/gate/flattening_filter/geometry/setRmax         20 cm
/gate/flattening_filter/geometry/setHeight       25 cm
/gate/flattening_filter/placement/setTranslation 0.0 0.0 10 cm
/gate/flattening_filter/vis/setVisible           0

	/gate/flattening_filter/daughters/name                 flattening_filter_cone1
	/gate/flattening_filter/daughters/insert               cone
	/gate/flattening_filter_cone1/setMaterial          Tungsten
	/gate/flattening_filter_cone1/geometry/setRmin2        0 cm  
	/gate/flattening_filter_cone1/geometry/setRmax2        0.001 cm
	/gate/flattening_filter_cone1/geometry/setRmin1        0 cm  
	/gate/flattening_filter_cone1/geometry/setRmax1        1.20 cm
	/gate/flattening_filter_cone1/geometry/setHeight       3.40 cm
	/gate/flattening_filter_cone1/placement/setTranslation 0.0 0.0 +10.35 cm
        /gate/flattening_filter_cone1/vis/setColor             yellow
        /gate/flattening_filter_cone1/vis/setVisible           1

	/gate/flattening_filter/daughters/name                 flattening_filter_cone2
	/gate/flattening_filter/daughters/insert               cone
	/gate/flattening_filter_cone2/setMaterial          Tungsten
	/gate/flattening_filter_cone2/geometry/setRmin2        0 cm  
	/gate/flattening_filter_cone2/geometry/setRmax2        1.20 cm
	/gate/flattening_filter_cone2/geometry/setRmin1        0 cm  
	/gate/flattening_filter_cone2/geometry/setRmax1        2.50 cm
	/gate/flattening_filter_cone2/geometry/setHeight       2.70 cm
	/gate/flattening_filter_cone2/placement/setTranslation 0.0 0.0 +7.3 cm
        /gate/flattening_filter_cone2/vis/setColor             yellow
        /gate/flattening_filter_cone2/vis/setVisible           1

	/gate/flattening_filter/daughters/name                 flattening_filter_cone3
	/gate/flattening_filter/daughters/insert               cone
	/gate/flattening_filter_cone3/setMaterial          Tungsten
	/gate/flattening_filter_cone3/geometry/setRmin2        0 cm  
	/gate/flattening_filter_cone3/geometry/setRmax2        2.50 cm
	/gate/flattening_filter_cone3/geometry/setRmin1        0 cm  
	/gate/flattening_filter_cone3/geometry/setRmax1        4.50 cm
	/gate/flattening_filter_cone3/geometry/setHeight       4.90 cm
	/gate/flattening_filter_cone3/placement/setTranslation 0.0 0.0 +3.5 cm
        /gate/flattening_filter_cone3/vis/setColor             yellow
        /gate/flattening_filter_cone3/vis/setVisible           1

	/gate/flattening_filter/daughters/name                 flattening_filter_cone4
	/gate/flattening_filter/daughters/insert               cone
	/gate/flattening_filter_cone4/setMaterial          Tungsten
	/gate/flattening_filter_cone4/geometry/setRmin2        0 cm  
	/gate/flattening_filter_cone4/geometry/setRmax2        4.50 cm
	/gate/flattening_filter_cone4/geometry/setRmin1        0 cm  
	/gate/flattening_filter_cone4/geometry/setRmax1        5.50 cm
	/gate/flattening_filter_cone4/geometry/setHeight       5.50 cm
	/gate/flattening_filter_cone4/placement/setTranslation 0.0 0.0 -1.7 cm
        /gate/flattening_filter_cone4/vis/setColor             yellow
        /gate/flattening_filter_cone4/vis/setVisible           1

	/gate/flattening_filter/daughters/name                 flattening_filter_cone5
	/gate/flattening_filter/daughters/insert               cone
	/gate/flattening_filter_cone5/setMaterial           Tungsten
	/gate/flattening_filter_cone5/geometry/setRmin2        0 cm  
	/gate/flattening_filter_cone5/geometry/setRmax2        5.50 cm
	/gate/flattening_filter_cone5/geometry/setRmin1        0 cm  
	/gate/flattening_filter_cone5/geometry/setRmax1        8.50 cm
	/gate/flattening_filter_cone5/geometry/setHeight       5.60 cm
	/gate/flattening_filter_cone5/placement/setTranslation 0.0 0.0 -7.25 cm
        /gate/flattening_filter_cone5/vis/setColor             yellow
        /gate/flattening_filter_cone5/vis/setVisible           1

	/gate/flattening_filter/daughters/name                 flattening_filter_cone6
	/gate/flattening_filter/daughters/insert               cone
	/gate/flattening_filter_cone6/setMaterial              Tungsten
	/gate/flattening_filter_cone6/geometry/setRmin2        0 cm  
	/gate/flattening_filter_cone6/geometry/setRmax2        8.50 cm
	/gate/flattening_filter_cone6/geometry/setRmin1        0 cm  
	/gate/flattening_filter_cone6/geometry/setRmax1        9.50 cm
	/gate/flattening_filter_cone6/geometry/setHeight       2.0 cm
	/gate/flattening_filter_cone6/placement/setTranslation 0.0 0.0 -11.05 cm
        /gate/flattening_filter_cone6/vis/setColor             yellow
        /gate/flattening_filter_cone6/vis/setVisible           1

